services:
  trfrmtestdatabase:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgrespass
    deploy:
      replicas: ${COMPOSE_DB_SCALE:-1}
    secrets:
      - postgrespass
    ports:
      - "127.0.0.1:15432-16432:5432"

secrets:
  postgrespass:
    file: ./postgrespass.secret
